sudo: true
language: bash
services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build
  - docker-compose run tests

#script:
#  - travis_wait docker-compose run deploy-testing
#
#deploy:
#  provider: script
#  script: docker-compose run deploy-production
#  on:
#    tags: true