sudo: required
language: bash
services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build
  - docker-compose run --rm tests

# Deploy to testing
script:
  - |
    travis_wait docker-compose run \
      -e ACCOUNT_ID=${TEST_ACCOUNT_ID} \
      -e AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID} \
      -e AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY} \
      -e REGION=${TEST_REGION} \
      -e SERVICE_NAME=${TEST_SERVICE_NAME} \
      -e STAGE=test \
      -e KEBOOLA_STACK=${TEST_SERVICE_NAME} \
      -e KBC_URL=https://connection.keboola.com \
      -e LOG_PORT=49730
      deploy

# Deploy to production
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
    tags: true
