sudo: required
language: bash
services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build
  - docker-compose run --rm tests

script:
  - travis_wait docker-compose run deploy-test

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
    tags: true
