sudo: required
language: bash
services:
  - docker

before_script:
  - docker -v
  - docker-compose -v

script:
  # unit tests
  - docker-compose run --rm tests

  # deploy to testing
  - >-
    docker-compose run --rm
    -e ACCOUNT_ID=${TEST_ACCOUNT_ID}
    -e AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID}
    -e AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY}
    -e REGION=${TEST_REGION}
    -e SERVICE_NAME=${TEST_SERVICE_NAME}
    -e STAGE=test
    -e KEBOOLA_STACK=${TEST_SERVICE_NAME}
    -e KBC_URL=${TEST_KBC_URL}
    -e DOCKER_RUNNER_URL=${TEST_KBC_DOCKER_RUNNER_URL}
    -e LOG_PORT=${TEST_LOG_PORT}
    deploy

# Deploy to production
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
    tags: true
