version: "2"

services:
  dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "3030:3000"
    environment:
      - ACCOUNT_ID
      - REGION
      - SERVICE_NAME
      - STAGE
      - KEBOOLA_STACK
      - KBC_URL
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
      - REDIRECT_URI_BASE
    command: >
             sh -c '
             serverless dynamodb install && serverless offline start --host 0.0.0.0
             '
  tests:
    build: .
    working_dir: /code
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test123
      - AWS_KMS_KEY_ID=test123
      - SERVICE_NAME=oauth-api-tests
      - STAGE=test
      - KEBOOLA_STACK=oauth-api-tests
      - KBC_URL=https://connection.keboola.com
      - SYRUP_URL=https://syrup.keboola.com
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
      - KBC_MANAGE_API_TOKEN=${TEST_KBC_MANAGE_API_TOKEN}
      - KBC_STORAGE_API_TOKEN=${TEST_KBC_STORAGE_API_TOKEN}
      - TW_APP_KEY
      - TW_APP_SECRET
    command: ./tests/run.sh
    links:
      - dynamodb

  dynamodb:
    image: quay.io/keboola/dynamodb-extractor-dynamodb

  deploy-dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - ACCOUNT_ID
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - REGION
      - SERVICE_NAME
      - STAGE=dev
      - KEBOOLA_STACK
      - KBC_URL
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
      - SLS_DEBUG=true
    command: serverless deploy

  deploy-test:
    build: .
    environment:
      - ACCOUNT_ID=${TEST_ACCOUNT_ID}
      - AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY}
      - REGION=${TEST_REGION}
      - SERVICE_NAME=${TEST_SERVICE_NAME}
      - STAGE=test
      - KEBOOLA_STACK=${TEST_SERVICE_NAME}
      - KBC_URL=https://connection.keboola.com
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
    command: serverless deploy

  deploy-prod-eu:
    build: .
    environment:
      - ACCOUNT_ID=${PROD_ACCOUNT_ID}
      - AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
      - REGION=eu-central-1
      - SERVICE_NAME=oauth-api-eu-central-1
      - STAGE=prod
      - KEBOOLA_STACK=oauth-api-eu-central-1
      - KBC_URL=https://connection.eu-central-1.keboola.com
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
    command: serverless deploy

  lint:
    build: .
    command: ./node_modules/.bin/eslint .
