version: "2"

services:
  dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "3030:3000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=${REGION}
      - REGION
      - SERVICE_NAME
      - STAGE=dev
      - KEBOOLA_STACK
      - KBC_URL
      - DOCKER_RUNNER_URL
      - DYNAMO_ENDPOINT=http://localhost:9000
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
      - REDIRECT_URI_BASE
      - SLS_DEBUG=true
      - LOG_PORT
    command: >
             sh -c '
             serverless dynamodb install && serverless offline start --host 0.0.0.0
             '

  deploy:
    build: .
    working_dir: /code
    environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - REGION
    - SERVICE_NAME
    - STAGE=dev
    - KEBOOLA_STACK
    - KBC_URL
    - SESSION_HASH_PREFIX
    - SESSION_COOKIE_NAME
    - SLS_DEBUG=true
    - LOG_PORT
    command: serverless deploy

  tests:
    build: .
    working_dir: /code
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test123
      - AWS_KMS_KEY_ID=test123
      - REGION=eu-central-1
      - SERVICE_NAME=oauth-api-tests
      - STAGE=test
      - KEBOOLA_STACK=oauth-api-tests
      - KBC_URL=https://connection.keboola.com
      - DOCKER_RUNNER_URL=https://docker-runner.keboola.com
      - DYNAMO_ENDPOINT=http://localstack:4569
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
      - KBC_MANAGE_API_TOKEN=${TEST_KBC_MANAGE_API_TOKEN}
      - KBC_STORAGE_API_TOKEN=${TEST_KBC_STORAGE_API_TOKEN}
      - TW_APP_KEY
      - TW_APP_SECRET
      - REDIRECT_URI_BASE
    command: ./tests/run.sh
    links:
      - localstack

  tests-dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test123
      - AWS_KMS_KEY_ID=test123
      - REGION=eu-central-1
      - SERVICE_NAME=oauth-api-tests
      - STAGE=test
      - KEBOOLA_STACK=oauth-api-tests
      - KBC_URL=https://connection.keboola.com
      - DOCKER_RUNNER_URL=https://docker-runner.keboola.com
      - DYNAMO_ENDPOINT=http://localstack:4569
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
      - KBC_MANAGE_API_TOKEN=${TEST_KBC_MANAGE_API_TOKEN}
      - KBC_STORAGE_API_TOKEN=${TEST_KBC_STORAGE_API_TOKEN}
      - TW_APP_KEY
      - TW_APP_SECRET
      - REDIRECT_URI_BASE
    command: ./tests/run.sh
    links:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "4569:4569"
    environment:
      - "SERVICES=dynamodb"
