version: "2"

services:
  dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "3030:3000"
    environment:
      - ACCOUNT_ID
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_KMS_KEY_ID
      - AWS_REGION
      - REGION
      - SERVICE_NAME
      - STAGE
      - KEBOOLA_STACK
      - KBC_URL
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
      - KBC_MANAGE_API_TOKEN
      - KBC_STORAGE_API_TOKEN
      - REDIRECT_URI_BASE
      - TW_APP_KEY
      - TW_APP_SECRET
    command: >
             sh -c '
             serverless dynamodb install && serverless offline start --host 0.0.0.0
             '
  tests:
    build: .
    working_dir: /code
    ports:
      - "3000:3000"
    environment:
      - "SERVICE_NAME=oauth-api-tests"
      - "STAGE=test"
      - "KEBOOLA_STACK=oauth-api-tests"
      - "KBC_URL=https://connection.keboola.com"
      - "SESSION_HASH_PREFIX"
      - "SESSION_COOKIE_NAME"
      - "KBC_MANAGE_API_TOKEN=${TEST_KBC_MANAGE_API_TOKEN}"
      - "KBC_STORAGE_API_TOKEN=${TEST_KBC_STORAGE_API_TOKEN}"
      - TW_APP_KEY
      - TW_APP_SECRET
    command: ./tests/run.sh

  deploy-dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - ACCOUNT_ID
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - REGION
      - AWS_KMS_KEY_ID
      - SERVICE_NAME
      - STAGE="dev"
      - KEBOOLA_STACK
      - KBC_URL
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
      - SLS_DEBUG=true
    command: >
             sh -c '
             serverless deploy
             '

  deploy-test:
    build: .
    environment:
      - "ACCOUNT_ID=${TEST_ACCOUNT_ID}"
      - "REGION=${TEST_REGION}"
      - "AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY}"
      - AWS_KMS_KEY_ID
      - "SERVICE_NAME=${TEST_SERVICE_NAME}"
      - "STAGE=test"
      - "KEBOOLA_STACK=${TEST_SERVICE_NAME}"
      - "KBC_URL=https://connection.keboola.com"
      - SESSION_HASH_PREFIX
      - SESSION_COOKIE_NAME
    command: >
             sh -c '
             serverless deploy
             '

  lint:
    build: .
    command: >
             sh -c '
             ./node_modules/.bin/eslint .
             '
