version: "2"

services:
  run-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "3000:3000"
    environment:
      - "AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY}"
      - "SERVICE_NAME=${TEST_SERVICE_NAME}"
      - "KEBOOLA_STACK=${TEST_KEBOOLA_STACK}"
      - "REGION=${TEST_REGION}"
      - "STAGE=${TEST_STAGE}"
      - "RDS_INSTANCE_CLASS=${TEST_RDS_INSTANCE_CLASS}"
      - "RDS_HOST=mysql"
      - "RDS_PORT=3306"
      - "RDS_USER=user"
      - "RDS_PASSWORD=password"
      - "RDS_DATABASE=gd_provisioning"
      - "LOG_HOST=${TEST_LOG_HOST}"
      - "LOG_PORT=${TEST_LOG_PORT}"
    command: >
             sh -c '
             serverless offline start --host 0.0.0.0
             '
