version: "2"

services:
  run-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "3000:3000"
    environment:
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "SERVICE_NAME=${SERVICE_NAME}"
      - "KEBOOLA_STACK=${KEBOOLA_STACK}"
      - "REGION=${REGION}"

    command: >
             sh -c '
             serverless offline start --host 0.0.0.0
             '
